//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AquaparkEntities2 : DbContext
    {
        private static AquaparkEntities2 _context;
        public AquaparkEntities2()
            : base("name=AquaparkEntities2")
        {
        }

        public static AquaparkEntities2 GetContext()
        {
            if (_context == null)
                _context = new AquaparkEntities2();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Абонимент> Абонимент { get; set; }
        public virtual DbSet<Аквапарк> Аквапарк { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Место_работы> Место_работы { get; set; }
        public virtual DbSet<Работник> Работник { get; set; }
        public virtual DbSet<Тип_аквапарка> Тип_аквапарка { get; set; }
    }
}
