//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аквапарк
    {
        public int id_аквапарка { get; set; }
        public int id_абонимента { get; set; }
        public int id_места { get; set; }
        public Nullable<int> id_типа { get; set; }
        public string Страна { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public int Дом { get; set; }
        public string Название { get; set; }
        public Nullable<bool> Обслуживание_инвалидов { get; set; }
    
        public virtual Абонимент Абонимент { get; set; }
        public virtual Место_работы Место_работы { get; set; }
        public virtual Тип_аквапарка Тип_аквапарка { get; set; }
    }
}
