//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Приложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class Место_работы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Место_работы()
        {
            this.Аквапарк = new HashSet<Аквапарк>();
        }
    
        public int id_места { get; set; }
        public Nullable<int> id_работника { get; set; }
        public string Сектор { get; set; }
        public string Аттракцион { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Аквапарк> Аквапарк { get; set; }
        public virtual Работник Работник { get; set; }
    }
}
